tags:
  - terraform

global:
  gateway: "192.168.1.1"
  dns_servers: ["192.168.1.1", "1.1.1.1"]
  node_name: "yrlab1"
  datastore_id: "local-lvm"
  pool_id: "k8s"
  boot_order: ["scsi0"]
  startup_order: 1
  startup_up_delay: 30
  machine: "q35"
  cpu_type: "host"
  network_bridge: "vmbr0"
  image_file: "talos-longhorn"
  os_type: "l26"
  description: "Talos Linux VM for Kubernetes cluster"

vms:
  talos-cp-01:
    enabled: true
    node_name: "yrlab1"
    vm_id: 111
    address: "192.168.1.111/24"
    cores: 3
    ram: 13312
    disk_size: 480
    startup_order: 1
    tags: ["talos", "kubernetes", "cp"]

  talos-cp-02:
    enabled: true
    node_name: "yrlab2"
    vm_id: 112
    address: "192.168.1.112/24"
    cores: 7
    ram: 13312
    disk_size: 210
    startup_order: 1
    tags: ["talos", "kubernetes", "cp"]
